# Generated by Django 5.1.1 on 2024-10-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_task_owner_alter_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-complete']},
        ),
    ]
